default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: develop
  password: develop
development:
  <<: *default
  database: authentication_api_development
test:
  <<: *default
  database: authentication_api_test
production:
  <<: *default
  database: authentication_api_production
  host: <%= Rails.application.credentials.database[:host] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
